[env:esp32-wroom-32ub-n8]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.flash_size = 8MB
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.partitions = default_8MB.csv
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  zinggjm/GxEPD2@^1.6.2
  adafruit/Adafruit GFX Library@^1.11.9
build_flags =
  -DCORE_DEBUG_LEVEL=3
