[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  zinggjm/GxEPD2@^1.6.2
  adafruit/Adafruit GFX Library@^1.11.9
build_flags =
  -DCORE_DEBUG_LEVEL=3

